### ISSUE TITLE
Props selectedStartDate and selectedEndDate does not work

### ISSUE THREAD

**Issue by YevhenLobanov** [stephy/CalendarPicker#122]
In index file those props are set to null by default and not handled when props are changed outside

**Comment by peacechen** [comment]
Thanks for catching that.  Would you mind creating a PR?

**Comment by YevhenLobanov** [comment]
Hello, I guess i need permission for this

**Comment by prashantm8** [comment]
also not working for me. please help me.

**Comment by YevhenLobanov** [comment]
@prashantm8 take a look in PR #123

**Comment by peacechen** [comment]
5.19.0 has been published.  Please try it out and close this issue if it works for you.

**Comment by YevhenLobanov** [comment]
@peacechen Could You please update npm package also, it is still 5.18

**Comment by peacechen** [comment]
It has already been published.  The npm website might be delayed.

**Comment by rolfb** [comment]
This seems to be causing a bug when the component updates as it drops existing state and rewrites from props.

**Comment by rolfb** [comment]
To clarify, if the calendar has internal state with new values for selectedStartDate and selectedEndDate and the componentDidUpdate triggers for a different reason than updating these two values from the outside, these values will get reset even if it has a newer internal value.  

https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker/index.js#L69-L78

**Comment by peacechen** [comment]
Good investigative work.  Would you try changing the comparison with `this.props.selectedStartDate` to `this.state.selectedStartDate` ?

https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker/index.js#L71

... and the equivalent for `selectedEndDate`.

It should be comparing its current & previous states instead of against props.

**Comment by rolfb** [comment]
I could, but I don't know the full intent of the code in the componentDidUpdate method - it looks like it should be refactored into something more comprehensible. componentDidUpdate should not call setState as that can create an infinite loop. The boolean value controlling when do call setState is a code smell as well. Perhaps @YevhenLobanov can show us his usage of this plugin so I can better understand the initial problem?

**Comment by peacechen** [comment]
Setting state in `componentDidUpdate` is standard practice in React.  Otherwise there'd be no way to update state when props change.
TBH this pattern is a fundamental issue with React.  I'm open to suggestions on how to improve the implementation.  We may need to leverage `shouldComponentUpdate`, one of React's ways of addressing and optimizing prop changes.

**Comment by rolfb** [comment]
Odd, didn't know it was "standard practice" - I've never had to resort to using it that way. But as mentioned before, I can refactor this when someone explains componentDidUpdate's requirements.

**Comment by peacechen** [comment]
I would like to see your approach to updating state when props change.  If there's a better way, I'm all for improving that.
The `doStateUpdate` flag is a way to gather all the prop changes that affect state, and call `setState` once at the end.  Otherwise there would be multiple `setState` calls in `componentDidUpdate` which is a performance hit.

**Comment by rolfb** [comment]
I'll have a look later, but still unclear about the acceptance criteria. Fwiw, multiple calls to setState and not passing a callback function ala `setState(() => // do something)` is batched and not a performance hit as far as I know.

**Comment by peacechen** [comment]
I've heard that setState is supposed to gather up multiple calls, but in practice I've found that to claim to be inaccurate.  In many instances I've seen back-to-back setState calls result in multiple re-renders.  If there's a guarantee that setState is optimized for that, we can refactor the code, but I don't trust it to behave optimally.

**Comment by rolfb** [comment]
I see your point, haven't checked to see when how long it batches for or what triggers it to execute it all.
