### ISSUE TITLE
[Improvement] Backwards range selection

### ISSUE THREAD

**Issue by vforvasile** [stephy/CalendarPicker#171]
When a date is selected, you can choose a date only in the future to get a range from that.

Would be cool to make it work backwards as well.

Behaviour: 
- Select a date, 
- Go in the Past, 
- Select another date, 
- A range is created

Any opinions?

**Comment by peacechen** [comment]
That would be a useful feature.  I recommend adding a prop such as `allowBackwardRangeSelect` to enable it.  The code would need to detect that the end date is before the start date, and flip them.  The returned start date should always be before the end date, even if selected backwards.
Would you be interesting in submitting a PR?

**Comment by arstropica** [comment]
Submitted a [PR](https://github.com/stephy/CalendarPicker/pull/195) for this.

**Comment by arstropica** [comment]
@peacechen 
I didn't want to clutter your master branch with comments, so I am posting my feedback in here.
The main reason I added the conditional logic to the `handleOnPressDay` event handler was because of usability issues that happened when introducing `allowBackwardRangeSelect`.
1. If past date(s) are already pre-populated, and `maxRangeDuration` &  `allowBackwardRangeSelect` are enabled, the calendar displays the current month with nothing selected.  You must touch Clear to regain selection options (which I think is a bit confusing for a first-time user)
![CalendarPicker-1](https://user-images.githubusercontent.com/6997672/80975502-2a536f80-8df0-11ea-93a9-e0b9a7f5ed00.jpg)
2. When you clear dates with `allowBackwardRangeSelect` & `maxRangeDuration` enabled and select a date in the future, the start & end dates are not reversed and a date range isn't created.
![CalendarPicker-2](https://user-images.githubusercontent.com/6997672/80975504-2aec0600-8df0-11ea-983b-8ea22c34f6a4.jpg)
3. If you select a change the start date with `allowBackwardRangeSelect` & `maxRangeDuration` enabled, the date range is still greater than the allowed limit. I am thinking that end date doesn't actually change, but the logic in `Day.js` only disables the dates exceeding `maxRangeDuration`.
![CalendarPicker-3](https://user-images.githubusercontent.com/6997672/80975506-2aec0600-8df0-11ea-924d-9d9083aff4ef.jpg)

These were all issues that I experienced when implementing `allowBackwardRangeSelect` and why I added the extra logic to `handleOnPressDay`.  I am not sure but I think that without some way of mitigating these corner cases, introducing `allowBackwardRangeSelect` may create more problems than it solves.

**Comment by peacechen** [comment]
@arstropica 
Are those issues from your fork, or the implementation in this library?  If it's in this library, post a new issue and we can debug.  Here are some thoughts before I forget them (copy to new issue):

1 & 2 : are you clearing selected dates through props, or calling the reset method?

3 : The min/max ranges assume the same start time each day.  A range starting on the 1st through the 5th is 4 days (5-1).  That range encompasses 5 calendar days, but the actual time duration is 4 * 24 hours.  If you need the range in calendar days, simply subtract 1 from the range passed in to the props.

**Comment by arstropica** [comment]
@peacechen 
The issues are from an install using https://github.com/stephy/CalendarPicker/commit/45611ced3f6ce4283b204e51f7078520662cd5ce tested with a `maxRangeDuration` of 5 and  `allowBackwardRangeSelect`.

**Comment by peacechen** [comment]
I'll debug as I have time.  If you have time, debug this by setting breakpoints in `node_modules/react-native-calendar-picker/CalendarPicker/index.js`.  These issues could be from not recalculating due to prop changes.  Are you clearing selected dates through props or calling the reset method?

**Comment by arstropica** [comment]
@peacechen 
Neither.  The issues were from https://github.com/stephy/CalendarPicker/commit/45611ced3f6ce4283b204e51f7078520662cd5ce on your master branch.

**Comment by peacechen** [comment]
You mentioned "When you clear dates with allowBackwardRangeSelect & maxRangeDuration enabled and select a date in the future" followed by a screenshot with a Clear button.  The buttons below the calendar are yours and not part of CalendarStrip.  What steps are they performing to clear the selections?  Please post your `<CalendarStrip>` code along with initial values and any methods that alter props or call CalendarStrip's internal methods.  A Snack that recreates the issue would also be helpful.

**Comment by peacechen** [comment]
I pushed a change that may fix cases 1-2.  I'm not sure how case 3 can happen.  Recreating your usage would help debug this faster.

**Comment by arstropica** [comment]
> Please post your `<CalendarStrip>` code along with initial values and any methods that alter props or call CalendarStrip's internal methods. A Snack that recreates the issue would also be helpful.
> 
Here you go: https://snack.expo.io/@estatesales/546e10

> You should either clear the selectedStartDate state in your component, or set the `intialDate` prop to the same value as selectedStartDate to have the calendar open to that month.
>
Clear calls the `resetSelections` method.

> I pushed a change that may fix cases 1-2. I'm not sure how case 3 can happen. Recreating your usage would help debug this faster.

I refer to your previous comment about the functionality for `allowBackwardRangeSelect`.
> I recommend adding a prop such as `allowBackwardRangeSelect` to enable it. The code would need to detect that the end date is before the start date, and flip them. The returned start date should always be before the end date, even if selected backwards.

If `maxRangeDuration` is set, `selectedEndDate <= selectedStartDate + maxRangeDuration`. 
See:
https://github.com/estatesales-org/CalendarPicker/blob/1be5d17261374b37ac2d229a432d4c6c55eb1ff1/CalendarPicker/index.js#L205
https://github.com/estatesales-org/CalendarPicker/blob/1be5d17261374b37ac2d229a432d4c6c55eb1ff1/CalendarPicker/index.js#L218

If the new date range is greater than the `maxRangeDuration`, you end up with case 3.

**Comment by peacechen** [comment]
Thanks for creating the Snack to recreate the issues you reported.  This helps debugging immensely.

I modified the example project to pass `selectedStartDate` and `selectedEndDate` props, along with a clear button and range enable toggle.  This recreated the issues you listed by exposing timing problems from state and prop changes.  It was firing the `onDateChange` callback before the async setState applied the changes, resulting in the original props overwriting the new values.  I pushed a fix that hopefully fixes the 3 issues you listed.  These types of problems are less prevalent with hooks, but that's a much larger refactor.

Try the latest version to validate whether it fixes the issues for you.  Note that you'll need to point the package.json directly to this repo instead of the 6.0.6 release in your Snack.
```
dependencies: {
    "react-native-calendar-picker": "https://github.com/stephy/CalendarPicker",
}
```


The example project in this repo is also another way to test this if that's more convenient.
https://github.com/stephy/CalendarPicker#sample-application

**Comment by peacechen** [comment]
Published in 6.1.0.  There were also other bugfixes that people were waiting for.  Let me know if you see any issues with this release.

**Comment by arstropica** [comment]
@peacechen Thanks.  I will do some testing next week.

**Comment by arstropica** [comment]
@peacechen Changes in 6.1.0 look good. Closing my fork.
Thanks.
