### ISSUE TITLE
Timezone Date displayed Issue

### ISSUE THREAD

**Issue by SpectorHacked** [stephy/CalendarPicker#192]
When getting the date and change it to different time zone, the displayed date use the phone timezone to choose the displayed dates,
Its possible to change the displayed dates according to specific timezone?

**Comment by peacechen** [comment]
The JS runtime uses the device's timezone.  Showing dates/times in another TZ can be tricky since date parsers take the source timezone into account and display in the device's current TZ.  

One approach is to parse the original datetime string and determine the year, month, and day without considering the TZ.
For example, let's say the device's TZ is -0400 UTC.  The source TZ is +0200 UTC in IS8601 format as `2020-04-12T04:10:53+02:00`.  Use a RegEx to retrieve year = 2020, month = 04, and day = 12.  Pass it to the moment constructor as `moment({year, month, day})`.

Technically the datetime won't be the same as the source's since the date's timezone will be constructed using the device's TZ.  For display purposes it does the job.  Note that when the user selects a date, you'll need to transform it back to the source's TZ.

**Comment by peacechen** [comment]
This is beyond the scope of this library.  If you find a good way to add this feature, please submit a PR.
