### ISSUE TITLE
Post install fail on 7.x

### ISSUE THREAD

**Issue by igorjos** [stephy/CalendarPicker#247]
```
errno ENOENT
npm ERR! react-native-calendar-picker@7.0.2 postinstall: `node-git-hooks`
npm ERR! spawn ENOENT

```
Environment
Ubuntu 20
Git v2.29.2
Npm v6.14.8
Node v14.15.0
RN: v0.62.2 and 0.63 same issue

**Comment by peacechen** [comment]
Does this still happen with the current release 7.0.7?  Some bugs were fixed in more recent releases of node-git-hooks. I recommend deleting node_modules and package-lock.json to ensure that your project gets the latest versions.

**Comment by wood1986** [comment]
@peacechen, I have already used the latest version. But I think the right fix should be using this library https://www.npmjs.com/package/pinst to rename the postinstall right before publishing the package. Otherwise, you are forcing all the consumers to run the git hook when doing npm install

husky also has the same tip for postinstall scenario https://typicode.github.io/husky/#/?id=install-1

As I do not see you automate the versioning and package publish, I am unable to create PR.
