### ISSUE TITLE
How can i do pull request to your project?

### ISSUE THREAD

**Issue by luisfuertes** [stephy/CalendarPicker#26]
I want do pull request with posibility of mark multiple dates. I try to clone your repository and do:

```
$ git checkout -b mark_multiple_dates_implemented
$ git checkout mark_multiple_dates_implemented
$ git push -u origin mark_multiple_dates_implemented
```
But:
> remote: Permission to stephy/CalendarPicker.git denied to luisfuertes.
> fatal: unable to access 'https://github.com/stephy/CalendarPicker.git/': The requested URL returned error: 403

Can you tell me how can i do please?

**Comment by MrOpposite** [comment]
What you're doing is branching this repository and trying to push to it.

You need to fork this repository, make your changes, and then create a pull-request, so that the developer of this project can pull from your own repository.

(You fork this repository by clicking the fork-button in the top right here on github)

**Comment by luisfuertes** [comment]
Thanks MrOpposite, problem solved
