### ISSUE TITLE
Selecting a date on current month swipes the calender to the month before

### ISSUE THREAD

**Issue by CostinBiserica** [stephy/CalendarPicker#262]
I have the following CalendarPicker setted:
[https://imgur.com/4vcgBXr](url). If I use the minDate as 12.12.2020 and maxDate as current date, (let's say 5.01.2020), when I try to select a range starting on any date from January, the calendar swipes to December (though selecting the date i've clicked) I have tried to change the minDate-maxDate interval to be in 2021, and the same happens anythime there are months before the date i've clicked to start the range. It's annoying because I have to swipe back to end the range selection.

**Comment by peacechen** [comment]
That sounds like a bug in the scroller. Please submit a PR if you have time to debug this.

**Comment by CostinBiserica** [comment]
> That sounds like a bug in the scroller. Please submit a PR if you have time to debug this.

I do not think I am able to do it as I am pretty new to this. I can add that the behaviour seems to happen only on android, as I tried on iOS but the range acts normal.

**Comment by peacechen** [comment]
This appears to be a bug within RecyclerListView. RLV watches its `extendedState` prop for changes to determine when to update itself. `selectedDate` is contained within `this.props.renderMonthParams`, and changing that triggers RLV to update. 
https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker/Scroller.js#L264

The initial visible month is set as index 30, and selecting a date on that month shouldn't change that index.  However on Android, RLV fires its callback `onVisibleIndicesChanged` and passes index 29 which is the month prior. This doesn't happen if a date is selected on another month. It only happens on the first date select on the initial month.

That bug in RLV needs to be fixed, but the author isn't responding so I have to add a work-around. When selectedDate changes on Android, it scrolls back to the selected date's month. It happens quickly and isn't very noticeable. Note that due to the use of setTimeout, running the app with the debugger connected will not fire the timer. Disconnect the debugger and the fix will work.

This fix needs more testing on Android and iOS devices before it's published. Please test this by pointing your package.json directly to this repo:
```
dependencies: {
    "react-native-calendar-picker": "https://github.com/stephy/CalendarPicker",
}
```

**Comment by peacechen** [comment]
@CostinBiserica This work-around fix has been published in 7.1.0. Does it work for you?

**Comment by CostinBiserica** [comment]
> @CostinBiserica This work-around fix has been published in 7.1.0. Does it work for you?

I have updated the library to 7.1.1. The swipe seems to still happen. I am testing on an Android 11 phone.

**Comment by rahulpunchh** [comment]
I am Facing same issue in android , any work around ?

**Comment by CostinBiserica** [comment]
As of 5.05.2021, with the library 7.1.1 it looks like the bug is fixed.
