### ISSUE TITLE
startDate in rangeSelection is giving null.

### ISSUE THREAD

**Issue by Shahanshah87** [stephy/CalendarPicker#281]
`<CalendarPicker
                                    startFromMonday={true}   
                                    allowRangeSelection={true}   
                                    onDateChange={onDateChange}
                                />`

this is my function:-
`const onDateChange = (date, type) => {
        console.log("changed date", date);
        if (type === 'END_DATE') {
            setState({
                ...state,
                endDate: date,
            });
        } else {
            setState({
                ...state,
                startDate: date,
                endDate: null,
            });
        }
    }`

When I am selecting for the first time it is giving correct date for both `startDate` and `endDate`. But after first time `startDate` is giving null.

**Comment by Shahanshah87** [comment]
@stephy please help!!!

**Comment by dominik-murar** [comment]
Having the issue as well. Seems like after first time END_DATE is invoked twice - once right after the START_DATE and second time when I select the end date.
![image](https://user-images.githubusercontent.com/79326595/116571802-b321c000-a90b-11eb-9dcc-3d1bbcf9d914.png)

**Comment by peacechen** [comment]
The Start and End date callbacks are intended behavior. When the user selects the start date in a range, there is no end date. CalendarPicker is informing the parent that the end date hasn't been selected yet. Otherwise the parent has no way of knowing that the end date has been cleared during a range selection. Consider this scenario without the end date null values:
First range selection --
Start Date selected 5/1
End Date selected 5/2

Second range selection --
Start Date selected 5/10
End Date selected 5/13

After the first range select, the parent' state is
Start Date 5/1
End Date 5/2

First pass, everything is good. However after the user selects the start date of a new date range, the parent's state is
Start Date 5/10
End Date 5/2

That would not reflect CalendarPicker's state.

**Comment by peacechen** [comment]
@Shahanshah87 
Does the issue also happen in the sample project? AFAIK it's been working for a while.
https://github.com/stephy/CalendarPicker#sample-application

**Comment by dominik-murar** [comment]
After some fiddeling around I found that it was just a problem with useState hook. I used an obejct for state `{startDate: null, endDate: null}`, and startDate update somehow got ignored with endDate being updated right away. I divided them into separate useState hooks and it alll works fine now.
