### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by edvinerikson** [stephy/CalendarPicker#4]
It would be nice if we could make this compatible (maybe it is) with NPM. 
Copy/paste the code isn't a good practice because everyone that is using the picker will need to manually update the code when we make changes.

**Comment by stephy** [comment]
Hi @edvinerikson, I think that's a great idea. I will work on that.

**Comment by stephy** [comment]
Hi @edvinerikson @brentvatne,  I successfully create an NPM package. All you have to do is:
npm install react-native-calendar-picker

However, since I have images, those did not get imported into the project. So inevitably if you try to use the calendar it will fail throwing the error: "Requiring unknown module "image!arrow-left". If you are sure the module is there, try restarting the packager.

I could change it back to have the images hosted on my website, or people would have to add the images manually.

Do any of two know how to make the images part of the package?

**Comment by stephy** [comment]
@edvinerikson, @brentvatne actually, anyone who downloads this today will also have to import the images manually I guess. Maybe I should remove the images and add plain text with arrows 
<   >

**Comment by stephy** [comment]
I actually updated it, removed the images completely and just added plain text. That way it has no dependencies and it works right out of the box. It now looks like this:
![screen shot 2015-04-14 at 12 19 39 am](https://cloud.githubusercontent.com/assets/773284/7132219/18c75200-e23c-11e4-86d4-da1bce39642c.png)

npm install react-native-calendar-picker should work :)

**Comment by edvinerikson** [comment]
It looks good!
But if we use the text variant instead of the arrows we will probably need to add some language translation ability (We may need this to Months/Week days).

So either we do that or we can try to find a solution to include those images, which i believe shouldn't be that hard. :smile:

**Comment by brentvatne** [comment]
Nice :smile: :100:
