### ISSUE TITLE
Any plans for date range

### ISSUE THREAD

**Issue by basequatro** [stephy/CalendarPicker#45]
I see that's on your TODO, but do you have any progress on this already?

**Comment by peacechen** [comment]
I would find this feature valuable as well.  It'll take some thought on how to design it so that selecting a range is intuitive.  Considerations:

- Drag region from start to end dates.
- Individually drag the start or end date (what if they're on the same day?).
- Tap start / end date to float it, tap again to place it down and select it.
- ???

The author @stephy may have abandoned this project unfortunately.  No commits or PR merges for over 7 months.

**Comment by stephy** [comment]
@peacechen @basequatro Sorry it has taken me so long to reply back to you but I have added this feature on v5 of the calendar picker.
Side note: v5 is a major rewrite of the calendar. Please see the Readme for more details.

**Comment by peacechen** [comment]
Thanks stephy.  Range selection is a super useful feature.
