### ISSUE TITLE
selectedDayColor didn't save after reopen calendar

### ISSUE THREAD

**Issue by northern-fox** [stephy/CalendarPicker#97]
Date is saved but marker didn't

**Comment by peacechen** [comment]
A prop `selectedDay` could be added so that the calendar's state can be reinstated after it's closed and re-opened.  PR's are welcome 😄 

For the time being, you could use the method `handleOnPressDay()` which takes the current day of the month (integer).  You'll need a ref to the CalendarPicker instance to call that method.
